version: '3'

services:
  vue_api:
    build: ./vue_api
    container_name: vue_api
    volumes:
      - ./vue_api/src/vue_api/:/usr/src/app/
    ports:
      - 8080:8080
    depends_on:
      - server

  rest_api:
    environment:
      PRODUCTION: 'false'

  database:
    ports:
      - 5432:5432